// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/demon_profiler.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto;
namespace operations_research {
class ConstraintRuns;
class ConstraintRunsDefaultTypeInternal;
extern ConstraintRunsDefaultTypeInternal _ConstraintRuns_default_instance_;
class DemonRuns;
class DemonRunsDefaultTypeInternal;
extern DemonRunsDefaultTypeInternal _DemonRuns_default_instance_;
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> ::operations_research::ConstraintRuns* Arena::CreateMaybeMessage<::operations_research::ConstraintRuns>(Arena*);
template<> ::operations_research::DemonRuns* Arena::CreateMaybeMessage<::operations_research::DemonRuns>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace operations_research {

// ===================================================================

class DemonRuns PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.DemonRuns) */ {
 public:
  inline DemonRuns() : DemonRuns(nullptr) {}
  virtual ~DemonRuns();

  DemonRuns(const DemonRuns& from);
  DemonRuns(DemonRuns&& from) noexcept
    : DemonRuns() {
    *this = ::std::move(from);
  }

  inline DemonRuns& operator=(const DemonRuns& from) {
    CopyFrom(from);
    return *this;
  }
  inline DemonRuns& operator=(DemonRuns&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DemonRuns& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DemonRuns* internal_default_instance() {
    return reinterpret_cast<const DemonRuns*>(
               &_DemonRuns_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DemonRuns& a, DemonRuns& b) {
    a.Swap(&b);
  }
  inline void Swap(DemonRuns* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DemonRuns* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DemonRuns* New() const final {
    return CreateMaybeMessage<DemonRuns>(nullptr);
  }

  DemonRuns* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DemonRuns>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DemonRuns& from);
  void MergeFrom(const DemonRuns& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DemonRuns* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.DemonRuns";
  }
  protected:
  explicit DemonRuns(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto);
    return ::descriptor_table_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartTimeFieldNumber = 2,
    kEndTimeFieldNumber = 3,
    kDemonIdFieldNumber = 1,
    kFailuresFieldNumber = 4,
  };
  // repeated int64 start_time = 2;
  int start_time_size() const;
  private:
  int _internal_start_time_size() const;
  public:
  void clear_start_time();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_start_time(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_start_time() const;
  void _internal_add_start_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_start_time();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 start_time(int index) const;
  void set_start_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_start_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      start_time() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_start_time();

  // repeated int64 end_time = 3;
  int end_time_size() const;
  private:
  int _internal_end_time_size() const;
  public:
  void clear_end_time();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_end_time(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_end_time() const;
  void _internal_add_end_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_end_time();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 end_time(int index) const;
  void set_end_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_end_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      end_time() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_end_time();

  // string demon_id = 1;
  void clear_demon_id();
  const std::string& demon_id() const;
  void set_demon_id(const std::string& value);
  void set_demon_id(std::string&& value);
  void set_demon_id(const char* value);
  void set_demon_id(const char* value, size_t size);
  std::string* mutable_demon_id();
  std::string* release_demon_id();
  void set_allocated_demon_id(std::string* demon_id);
  private:
  const std::string& _internal_demon_id() const;
  void _internal_set_demon_id(const std::string& value);
  std::string* _internal_mutable_demon_id();
  public:

  // int64 failures = 4;
  void clear_failures();
  ::PROTOBUF_NAMESPACE_ID::int64 failures() const;
  void set_failures(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_failures() const;
  void _internal_set_failures(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.DemonRuns)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > start_time_;
  mutable std::atomic<int> _start_time_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > end_time_;
  mutable std::atomic<int> _end_time_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr demon_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 failures_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto;
};
// -------------------------------------------------------------------

class ConstraintRuns PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.ConstraintRuns) */ {
 public:
  inline ConstraintRuns() : ConstraintRuns(nullptr) {}
  virtual ~ConstraintRuns();

  ConstraintRuns(const ConstraintRuns& from);
  ConstraintRuns(ConstraintRuns&& from) noexcept
    : ConstraintRuns() {
    *this = ::std::move(from);
  }

  inline ConstraintRuns& operator=(const ConstraintRuns& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConstraintRuns& operator=(ConstraintRuns&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConstraintRuns& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConstraintRuns* internal_default_instance() {
    return reinterpret_cast<const ConstraintRuns*>(
               &_ConstraintRuns_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ConstraintRuns& a, ConstraintRuns& b) {
    a.Swap(&b);
  }
  inline void Swap(ConstraintRuns* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConstraintRuns* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConstraintRuns* New() const final {
    return CreateMaybeMessage<ConstraintRuns>(nullptr);
  }

  ConstraintRuns* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConstraintRuns>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConstraintRuns& from);
  void MergeFrom(const ConstraintRuns& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConstraintRuns* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.ConstraintRuns";
  }
  protected:
  explicit ConstraintRuns(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto);
    return ::descriptor_table_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInitialPropagationStartTimeFieldNumber = 2,
    kInitialPropagationEndTimeFieldNumber = 3,
    kDemonsFieldNumber = 5,
    kConstraintIdFieldNumber = 1,
    kFailuresFieldNumber = 4,
  };
  // repeated int64 initial_propagation_start_time = 2;
  int initial_propagation_start_time_size() const;
  private:
  int _internal_initial_propagation_start_time_size() const;
  public:
  void clear_initial_propagation_start_time();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_initial_propagation_start_time(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_initial_propagation_start_time() const;
  void _internal_add_initial_propagation_start_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_initial_propagation_start_time();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 initial_propagation_start_time(int index) const;
  void set_initial_propagation_start_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_initial_propagation_start_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      initial_propagation_start_time() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_initial_propagation_start_time();

  // repeated int64 initial_propagation_end_time = 3;
  int initial_propagation_end_time_size() const;
  private:
  int _internal_initial_propagation_end_time_size() const;
  public:
  void clear_initial_propagation_end_time();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_initial_propagation_end_time(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_initial_propagation_end_time() const;
  void _internal_add_initial_propagation_end_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_initial_propagation_end_time();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 initial_propagation_end_time(int index) const;
  void set_initial_propagation_end_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_initial_propagation_end_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      initial_propagation_end_time() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_initial_propagation_end_time();

  // repeated .operations_research.DemonRuns demons = 5;
  int demons_size() const;
  private:
  int _internal_demons_size() const;
  public:
  void clear_demons();
  ::operations_research::DemonRuns* mutable_demons(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::DemonRuns >*
      mutable_demons();
  private:
  const ::operations_research::DemonRuns& _internal_demons(int index) const;
  ::operations_research::DemonRuns* _internal_add_demons();
  public:
  const ::operations_research::DemonRuns& demons(int index) const;
  ::operations_research::DemonRuns* add_demons();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::DemonRuns >&
      demons() const;

  // string constraint_id = 1;
  void clear_constraint_id();
  const std::string& constraint_id() const;
  void set_constraint_id(const std::string& value);
  void set_constraint_id(std::string&& value);
  void set_constraint_id(const char* value);
  void set_constraint_id(const char* value, size_t size);
  std::string* mutable_constraint_id();
  std::string* release_constraint_id();
  void set_allocated_constraint_id(std::string* constraint_id);
  private:
  const std::string& _internal_constraint_id() const;
  void _internal_set_constraint_id(const std::string& value);
  std::string* _internal_mutable_constraint_id();
  public:

  // int64 failures = 4;
  void clear_failures();
  ::PROTOBUF_NAMESPACE_ID::int64 failures() const;
  void set_failures(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_failures() const;
  void _internal_set_failures(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.ConstraintRuns)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > initial_propagation_start_time_;
  mutable std::atomic<int> _initial_propagation_start_time_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > initial_propagation_end_time_;
  mutable std::atomic<int> _initial_propagation_end_time_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::DemonRuns > demons_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr constraint_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 failures_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DemonRuns

// string demon_id = 1;
inline void DemonRuns::clear_demon_id() {
  demon_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& DemonRuns::demon_id() const {
  // @@protoc_insertion_point(field_get:operations_research.DemonRuns.demon_id)
  return _internal_demon_id();
}
inline void DemonRuns::set_demon_id(const std::string& value) {
  _internal_set_demon_id(value);
  // @@protoc_insertion_point(field_set:operations_research.DemonRuns.demon_id)
}
inline std::string* DemonRuns::mutable_demon_id() {
  // @@protoc_insertion_point(field_mutable:operations_research.DemonRuns.demon_id)
  return _internal_mutable_demon_id();
}
inline const std::string& DemonRuns::_internal_demon_id() const {
  return demon_id_.Get();
}
inline void DemonRuns::_internal_set_demon_id(const std::string& value) {
  
  demon_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void DemonRuns::set_demon_id(std::string&& value) {
  
  demon_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:operations_research.DemonRuns.demon_id)
}
inline void DemonRuns::set_demon_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  demon_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:operations_research.DemonRuns.demon_id)
}
inline void DemonRuns::set_demon_id(const char* value,
    size_t size) {
  
  demon_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:operations_research.DemonRuns.demon_id)
}
inline std::string* DemonRuns::_internal_mutable_demon_id() {
  
  return demon_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* DemonRuns::release_demon_id() {
  // @@protoc_insertion_point(field_release:operations_research.DemonRuns.demon_id)
  return demon_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DemonRuns::set_allocated_demon_id(std::string* demon_id) {
  if (demon_id != nullptr) {
    
  } else {
    
  }
  demon_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), demon_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:operations_research.DemonRuns.demon_id)
}

// repeated int64 start_time = 2;
inline int DemonRuns::_internal_start_time_size() const {
  return start_time_.size();
}
inline int DemonRuns::start_time_size() const {
  return _internal_start_time_size();
}
inline void DemonRuns::clear_start_time() {
  start_time_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::_internal_start_time(int index) const {
  return start_time_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::start_time(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.DemonRuns.start_time)
  return _internal_start_time(index);
}
inline void DemonRuns::set_start_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  start_time_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.DemonRuns.start_time)
}
inline void DemonRuns::_internal_add_start_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  start_time_.Add(value);
}
inline void DemonRuns::add_start_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_start_time(value);
  // @@protoc_insertion_point(field_add:operations_research.DemonRuns.start_time)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
DemonRuns::_internal_start_time() const {
  return start_time_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
DemonRuns::start_time() const {
  // @@protoc_insertion_point(field_list:operations_research.DemonRuns.start_time)
  return _internal_start_time();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
DemonRuns::_internal_mutable_start_time() {
  return &start_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
DemonRuns::mutable_start_time() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.DemonRuns.start_time)
  return _internal_mutable_start_time();
}

// repeated int64 end_time = 3;
inline int DemonRuns::_internal_end_time_size() const {
  return end_time_.size();
}
inline int DemonRuns::end_time_size() const {
  return _internal_end_time_size();
}
inline void DemonRuns::clear_end_time() {
  end_time_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::_internal_end_time(int index) const {
  return end_time_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::end_time(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.DemonRuns.end_time)
  return _internal_end_time(index);
}
inline void DemonRuns::set_end_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  end_time_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.DemonRuns.end_time)
}
inline void DemonRuns::_internal_add_end_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  end_time_.Add(value);
}
inline void DemonRuns::add_end_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_end_time(value);
  // @@protoc_insertion_point(field_add:operations_research.DemonRuns.end_time)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
DemonRuns::_internal_end_time() const {
  return end_time_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
DemonRuns::end_time() const {
  // @@protoc_insertion_point(field_list:operations_research.DemonRuns.end_time)
  return _internal_end_time();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
DemonRuns::_internal_mutable_end_time() {
  return &end_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
DemonRuns::mutable_end_time() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.DemonRuns.end_time)
  return _internal_mutable_end_time();
}

// int64 failures = 4;
inline void DemonRuns::clear_failures() {
  failures_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::_internal_failures() const {
  return failures_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 DemonRuns::failures() const {
  // @@protoc_insertion_point(field_get:operations_research.DemonRuns.failures)
  return _internal_failures();
}
inline void DemonRuns::_internal_set_failures(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  failures_ = value;
}
inline void DemonRuns::set_failures(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_failures(value);
  // @@protoc_insertion_point(field_set:operations_research.DemonRuns.failures)
}

// -------------------------------------------------------------------

// ConstraintRuns

// string constraint_id = 1;
inline void ConstraintRuns::clear_constraint_id() {
  constraint_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ConstraintRuns::constraint_id() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintRuns.constraint_id)
  return _internal_constraint_id();
}
inline void ConstraintRuns::set_constraint_id(const std::string& value) {
  _internal_set_constraint_id(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintRuns.constraint_id)
}
inline std::string* ConstraintRuns::mutable_constraint_id() {
  // @@protoc_insertion_point(field_mutable:operations_research.ConstraintRuns.constraint_id)
  return _internal_mutable_constraint_id();
}
inline const std::string& ConstraintRuns::_internal_constraint_id() const {
  return constraint_id_.Get();
}
inline void ConstraintRuns::_internal_set_constraint_id(const std::string& value) {
  
  constraint_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ConstraintRuns::set_constraint_id(std::string&& value) {
  
  constraint_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:operations_research.ConstraintRuns.constraint_id)
}
inline void ConstraintRuns::set_constraint_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  constraint_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:operations_research.ConstraintRuns.constraint_id)
}
inline void ConstraintRuns::set_constraint_id(const char* value,
    size_t size) {
  
  constraint_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:operations_research.ConstraintRuns.constraint_id)
}
inline std::string* ConstraintRuns::_internal_mutable_constraint_id() {
  
  return constraint_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ConstraintRuns::release_constraint_id() {
  // @@protoc_insertion_point(field_release:operations_research.ConstraintRuns.constraint_id)
  return constraint_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConstraintRuns::set_allocated_constraint_id(std::string* constraint_id) {
  if (constraint_id != nullptr) {
    
  } else {
    
  }
  constraint_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), constraint_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:operations_research.ConstraintRuns.constraint_id)
}

// repeated int64 initial_propagation_start_time = 2;
inline int ConstraintRuns::_internal_initial_propagation_start_time_size() const {
  return initial_propagation_start_time_.size();
}
inline int ConstraintRuns::initial_propagation_start_time_size() const {
  return _internal_initial_propagation_start_time_size();
}
inline void ConstraintRuns::clear_initial_propagation_start_time() {
  initial_propagation_start_time_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::_internal_initial_propagation_start_time(int index) const {
  return initial_propagation_start_time_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::initial_propagation_start_time(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintRuns.initial_propagation_start_time)
  return _internal_initial_propagation_start_time(index);
}
inline void ConstraintRuns::set_initial_propagation_start_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  initial_propagation_start_time_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintRuns.initial_propagation_start_time)
}
inline void ConstraintRuns::_internal_add_initial_propagation_start_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  initial_propagation_start_time_.Add(value);
}
inline void ConstraintRuns::add_initial_propagation_start_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_initial_propagation_start_time(value);
  // @@protoc_insertion_point(field_add:operations_research.ConstraintRuns.initial_propagation_start_time)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
ConstraintRuns::_internal_initial_propagation_start_time() const {
  return initial_propagation_start_time_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
ConstraintRuns::initial_propagation_start_time() const {
  // @@protoc_insertion_point(field_list:operations_research.ConstraintRuns.initial_propagation_start_time)
  return _internal_initial_propagation_start_time();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
ConstraintRuns::_internal_mutable_initial_propagation_start_time() {
  return &initial_propagation_start_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
ConstraintRuns::mutable_initial_propagation_start_time() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.ConstraintRuns.initial_propagation_start_time)
  return _internal_mutable_initial_propagation_start_time();
}

// repeated int64 initial_propagation_end_time = 3;
inline int ConstraintRuns::_internal_initial_propagation_end_time_size() const {
  return initial_propagation_end_time_.size();
}
inline int ConstraintRuns::initial_propagation_end_time_size() const {
  return _internal_initial_propagation_end_time_size();
}
inline void ConstraintRuns::clear_initial_propagation_end_time() {
  initial_propagation_end_time_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::_internal_initial_propagation_end_time(int index) const {
  return initial_propagation_end_time_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::initial_propagation_end_time(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintRuns.initial_propagation_end_time)
  return _internal_initial_propagation_end_time(index);
}
inline void ConstraintRuns::set_initial_propagation_end_time(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  initial_propagation_end_time_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintRuns.initial_propagation_end_time)
}
inline void ConstraintRuns::_internal_add_initial_propagation_end_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  initial_propagation_end_time_.Add(value);
}
inline void ConstraintRuns::add_initial_propagation_end_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_initial_propagation_end_time(value);
  // @@protoc_insertion_point(field_add:operations_research.ConstraintRuns.initial_propagation_end_time)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
ConstraintRuns::_internal_initial_propagation_end_time() const {
  return initial_propagation_end_time_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
ConstraintRuns::initial_propagation_end_time() const {
  // @@protoc_insertion_point(field_list:operations_research.ConstraintRuns.initial_propagation_end_time)
  return _internal_initial_propagation_end_time();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
ConstraintRuns::_internal_mutable_initial_propagation_end_time() {
  return &initial_propagation_end_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
ConstraintRuns::mutable_initial_propagation_end_time() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.ConstraintRuns.initial_propagation_end_time)
  return _internal_mutable_initial_propagation_end_time();
}

// int64 failures = 4;
inline void ConstraintRuns::clear_failures() {
  failures_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::_internal_failures() const {
  return failures_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ConstraintRuns::failures() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintRuns.failures)
  return _internal_failures();
}
inline void ConstraintRuns::_internal_set_failures(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  failures_ = value;
}
inline void ConstraintRuns::set_failures(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_failures(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintRuns.failures)
}

// repeated .operations_research.DemonRuns demons = 5;
inline int ConstraintRuns::_internal_demons_size() const {
  return demons_.size();
}
inline int ConstraintRuns::demons_size() const {
  return _internal_demons_size();
}
inline void ConstraintRuns::clear_demons() {
  demons_.Clear();
}
inline ::operations_research::DemonRuns* ConstraintRuns::mutable_demons(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.ConstraintRuns.demons)
  return demons_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::DemonRuns >*
ConstraintRuns::mutable_demons() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.ConstraintRuns.demons)
  return &demons_;
}
inline const ::operations_research::DemonRuns& ConstraintRuns::_internal_demons(int index) const {
  return demons_.Get(index);
}
inline const ::operations_research::DemonRuns& ConstraintRuns::demons(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintRuns.demons)
  return _internal_demons(index);
}
inline ::operations_research::DemonRuns* ConstraintRuns::_internal_add_demons() {
  return demons_.Add();
}
inline ::operations_research::DemonRuns* ConstraintRuns::add_demons() {
  // @@protoc_insertion_point(field_add:operations_research.ConstraintRuns.demons)
  return _internal_add_demons();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::DemonRuns >&
ConstraintRuns::demons() const {
  // @@protoc_insertion_point(field_list:operations_research.ConstraintRuns.demons)
  return demons_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fdemon_5fprofiler_2eproto
